In [1]:
# Importing Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import re
import nltk
nltk.download('stopwords') #downloads the required list of words that we need to remove
from nltk.corpus import stopwords # importing 'stopwords' to this notebook
from nltk.stem import WordNetLemmatizer # For Lemmitization

import joblib

[nltk_data] Downloading package stopwords to /usr/share/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [2]:
# Importing combined data(news and label)
data= pd.read_csv('../input/stocknews/Combined_News_DJIA.csv')
data.head(2)

Date  Label                                               Top1  \
0  2008-08-08      0  b"Georgia 'downs two Russian warplanes' as cou...   
1  2008-08-11      1  b'Why wont America and Nato help us? If they w...   

                                          Top2  \
0      b'BREAKING: Musharraf to be impeached.'   
1  b'Bush puts foot down on Georgian conflict'   

                                                Top3  \
0  b'Russia Today: Columns of troops roll into So...   
1  b"Jewish Georgian minister: Thanks to Israeli ...   

                                                Top4  \
0  b'Russian tanks are moving towards the capital...   
1  b'Georgian army flees in disarray as Russians ...   

                                                Top5  \
0  b"Afghan children raped with 'impunity,' U.N. ...   
1      b"Olympic opening ceremony fireworks 'faked'"   

                                                Top6  \
0  b'150 Russian tanks have entered South Ossetia...   
1  b'What were the Mossad with fraudulent New Zea...   

                                                Top7  \
0  b"Breaking: Georgia invades South Ossetia, Rus...   
1  b'Russia angered by Israeli military sale to G...   

                                                Top8  ...  \
0  b"The 'enemy combatent' trials are nothing but...  ...   
1  b'An American citizen living in S.Ossetia blam...  ...   

                                               Top16  \
0  b'Georgia Invades South Ossetia - if Russia ge...   
1  b'Israel and the US behind the Georgian aggres...   

                                               Top17  \
0                b'Al-Qaeda Faces Islamist Backlash'   
1  b'"Do not believe TV, neither Russian nor Geor...   

                                               Top18  \
0  b'Condoleezza Rice: "The US would not act to p...   
1  b'Riots are still going on in Montreal (Canada...   

                                               Top19  \
0  b'This is a busy day:  The European Union has ...   
1    b'China to overtake US as largest manufacturer'   

                                               Top20  \
0  b"Georgia will withdraw 1,000 soldiers from Ir...   
1                     b'War in South Ossetia [PICS]'   

                                               Top21  \
0  b'Why the Pentagon Thinks Attacking Iran is a ...   
1  b'Israeli Physicians Group Condemns State Tort...   

                                               Top22  \
0  b'Caucasus in crisis: Georgia invades South Os...   
1  b' Russia has just beaten the United States ov...   

                                               Top23  \
0  b'Indian shoe manufactory  - And again in a se...   
1  b'Perhaps *the* question about the Georgia - R...   

                                               Top24  \
0  b'Visitors Suffering from Mental Illnesses Ban...   
1                 b'Russia is so much better at war'   

                                               Top25  
0           b"No Help for Mexico's Kidnapping Surge"  
1  b"So this is what it's come to: trading sex fo...  

[2 rows x 27 columns]

In [3]:
# Stock data
price_info= pd.read_csv("../input/stocknews/upload_DJIA_table.csv")
price_info= price_info.reindex(index=data.index[::-1]) # Inverting the index of dataset
price_info= price_info.set_index(i for i in range(0, len(price_info))) # Setting new index
price_info.head()

Date          Open          High           Low         Close  \
0  2008-08-08  11432.089844  11759.959961  11388.040039  11734.320312   
1  2008-08-11  11729.669922  11867.110352  11675.530273  11782.349609   
2  2008-08-12  11781.700195  11782.349609  11601.519531  11642.469727   
3  2008-08-13  11632.809570  11633.780273  11453.339844  11532.959961   
4  2008-08-14  11532.070312  11718.280273  11450.889648  11615.929688   

      Volume     Adj Close  
0  212830000  11734.320312  
1  183190000  11782.349609  
2  173590000  11642.469727  
3  182550000  11532.959961  
4  159790000  11615.929688

In [4]:
# Changing Labels for Intraday status of DJIA
for i in range(len(data)):
    if price_info["Close"][i] - price_info["Open"][i] >= 0: # Price rose (or) stayed same
        data["Label"][i]= 1
    elif price_info["Close"][i] - price_info["Open"][i] < 0: # Price decreased
        data["Label"][i]= 0
        
data.head(2)

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


Date  Label                                               Top1  \
0  2008-08-08      1  b"Georgia 'downs two Russian warplanes' as cou...   
1  2008-08-11      1  b'Why wont America and Nato help us? If they w...   

                                          Top2  \
0      b'BREAKING: Musharraf to be impeached.'   
1  b'Bush puts foot down on Georgian conflict'   

                                                Top3  \
0  b'Russia Today: Columns of troops roll into So...   
1  b"Jewish Georgian minister: Thanks to Israeli ...   

                                                Top4  \
0  b'Russian tanks are moving towards the capital...   
1  b'Georgian army flees in disarray as Russians ...   

                                                Top5  \
0  b"Afghan children raped with 'impunity,' U.N. ...   
1      b"Olympic opening ceremony fireworks 'faked'"   

                                                Top6  \
0  b'150 Russian tanks have entered South Ossetia...   
1  b'What were the Mossad with fraudulent New Zea...   

                                                Top7  \
0  b"Breaking: Georgia invades South Ossetia, Rus...   
1  b'Russia angered by Israeli military sale to G...   

                                                Top8  ...  \
0  b"The 'enemy combatent' trials are nothing but...  ...   
1  b'An American citizen living in S.Ossetia blam...  ...   

                                               Top16  \
0  b'Georgia Invades South Ossetia - if Russia ge...   
1  b'Israel and the US behind the Georgian aggres...   

                                               Top17  \
0                b'Al-Qaeda Faces Islamist Backlash'   
1  b'"Do not believe TV, neither Russian nor Geor...   

                                               Top18  \
0  b'Condoleezza Rice: "The US would not act to p...   
1  b'Riots are still going on in Montreal (Canada...   

                                               Top19  \
0  b'This is a busy day:  The European Union has ...   
1    b'China to overtake US as largest manufacturer'   

                                               Top20  \
0  b"Georgia will withdraw 1,000 soldiers from Ir...   
1                     b'War in South Ossetia [PICS]'   

                                               Top21  \
0  b'Why the Pentagon Thinks Attacking Iran is a ...   
1  b'Israeli Physicians Group Condemns State Tort...   

                                               Top22  \
0  b'Caucasus in crisis: Georgia invades South Os...   
1  b' Russia has just beaten the United States ov...   

                                               Top23  \
0  b'Indian shoe manufactory  - And again in a se...   
1  b'Perhaps *the* question about the Georgia - R...   

                                               Top24  \
0  b'Visitors Suffering from Mental Illnesses Ban...   
1                 b'Russia is so much better at war'   

                                               Top25  
0           b"No Help for Mexico's Kidnapping Surge"  
1  b"So this is what it's come to: trading sex fo...  

[2 rows x 27 columns]

# Data Preprocessing

In [5]:
# Making 1 day past news uselful for next day
date_label= data[['Date', 'Label']]
tops= data.drop(columns= ['Date', 'Label'])

date_label= date_label.loc[1:len(date_label)] # Removing 1st Date Entry
tops=tops.loc[0:len(date_label)-1] # Removing last News Entry

date_label= date_label.set_index(i for i in range(0, len(date_label))) # Setting Index for date_label
tops= tops.set_index(i for i in range(0, len(tops))) # Setting Index for tops

len(date_label), len(tops)

(1988, 1988)

In [6]:
data_new= pd.concat([date_label, tops], axis=1, sort=False) # Joining date_lable and tops
display(data_new.head())
display(data_new.tail())

Date  Label                                               Top1  \
0  2008-08-11      1  b"Georgia 'downs two Russian warplanes' as cou...   
1  2008-08-12      0  b'Why wont America and Nato help us? If they w...   
2  2008-08-13      0  b'Remember that adorable 9-year-old who sang a...   
3  2008-08-14      1  b' U.S. refuses Israel weapons to attack Iran:...   
4  2008-08-15      1  b'All the experts admit that we should legalis...   

                                                Top2  \
0            b'BREAKING: Musharraf to be impeached.'   
1        b'Bush puts foot down on Georgian conflict'   
2                 b"Russia 'ends Georgia operation'"   
3  b"When the president ordered to attack Tskhinv...   
4  b'War in South Osetia - 89 pictures made by a ...   

                                                Top3  \
0  b'Russia Today: Columns of troops roll into So...   
1  b"Jewish Georgian minister: Thanks to Israeli ...   
2  b'"If we had no sexual harassment we would hav...   
3  b' Israel clears troops who killed Reuters cam...   
4  b'Swedish wrestler Ara Abrahamian throws away ...   

                                                Top4  \
0  b'Russian tanks are moving towards the capital...   
1  b'Georgian army flees in disarray as Russians ...   
2  b"Al-Qa'eda is losing support in Iraq because ...   
3  b'Britain\'s policy of being tough on drugs is...   
4  b'Russia exaggerated the death toll in South O...   

                                                Top5  \
0  b"Afghan children raped with 'impunity,' U.N. ...   
1      b"Olympic opening ceremony fireworks 'faked'"   
2  b'Ceasefire in Georgia: Putin Outmaneuvers the...   
3  b'Body of 14 year old found in trunk; Latest (...   
4  b'Missile That Killed 9 Inside Pakistan May Ha...   

                                                Top6  \
0  b'150 Russian tanks have entered South Ossetia...   
1  b'What were the Mossad with fraudulent New Zea...   
2  b'Why Microsoft and Intel tried to kill the XO...   
3  b'China has moved 10 *million* quake survivors...   
4  b"Rushdie Condemns Random House's Refusal to P...   

                                                Top7  \
0  b"Breaking: Georgia invades South Ossetia, Rus...   
1  b'Russia angered by Israeli military sale to G...   
2  b'Stratfor: The Russo-Georgian War and the Bal...   
3  b"Bush announces Operation Get All Up In Russi...   
4  b'Poland and US agree to missle defense deal. ...   

                                                Top8  ...  \
0  b"The 'enemy combatent' trials are nothing but...  ...   
1  b'An American citizen living in S.Ossetia blam...  ...   
2  b"I'm Trying to Get a Sense of This Whole Geor...  ...   
3             b'Russian forces sink Georgian ships '  ...   
4  b'Will the Russians conquer Tblisi? Bet on it,...  ...   

                                               Top16  \
0  b'Georgia Invades South Ossetia - if Russia ge...   
1  b'Israel and the US behind the Georgian aggres...   
2  b'U.S. troops still in Georgia (did you know t...   
3                      b'Elephants extinct by 2020?'   
4  b'Bank analyst forecast Georgian crisis 2 days...   

                                               Top17  \
0                b'Al-Qaeda Faces Islamist Backlash'   
1  b'"Do not believe TV, neither Russian nor Geor...   
2       b'Why Russias response to Georgia was right'   
3  b'US humanitarian missions soon in Georgia - i...   
4  b"Georgia confict could set back Russia's US r...   

                                               Top18  \
0  b'Condoleezza Rice: "The US would not act to p...   
1  b'Riots are still going on in Montreal (Canada...   
2  b'Gorbachev accuses U.S. of making a "serious ...   
3             b"Georgia's DDOS came from US sources"   
4  b'War in the Caucasus is as much the product o...   

                                               Top19  \
0  b'This is a busy day:  The European Union has ...   
1    b'China to overtake US as largest manufac

Date  Label                                               Top1  \
1983  2016-06-27      0  David Cameron to Resign as PM After EU Referendum   
1984  2016-06-28      1  Barclays and RBS shares suspended from trading...   
1985  2016-06-29      1  2,500 Scientists To Australia: If You Want To ...   
1986  2016-06-30      1                   Explosion At Airport In Istanbul   
1987  2016-07-01      1  Jamaica proposes marijuana dispensers for tour...   

                                                   Top2  \
1983  BBC forecasts UK votes to Leave the European U...   
1984  Pope says Church should ask forgiveness from g...   
1985  The personal details of 112,000 French police ...   
1986  Yemeni former president: Terrorism is the offs...   
1987  Stephen Hawking says pollution and 'stupidity'...   

                                                   Top3  \
1983  Nicola Sturgeon says a second independence ref...   
1984  Poland 'shocked' by xenophobic abuse of Poles ...   
1985  S&amp;P cuts United Kingdom sovereign credit r...   
1986  UK must accept freedom of movement to access E...   
1987  Boris Johnson says he will not run for Tory pa...   

                                                   Top4  \
1983  It's official. Britain votes to leave the Euro...   
1984  There will be no second referendum, cabinet ag...   
1985                Huge helium deposit found in Africa   
1986  Devastated: scientists too late to captive bre...   
1987  Six gay men in Ivory Coast were abused and for...   

                                                   Top5  \
1983  World's Largest Tibetan Buddhist Institute Ord...   
1984      Scotland welcome to join EU, Merkel ally says   
1985  CEO of the South African state broadcaster qui...   
1986  British Labor Party leader Jeremy Corbyn loses...   
1987  Switzerland denies citizenship to Muslim immig...   

                                                   Top6  \
1983  Not a single place in Scotland voted to leave ...   
1984  Sterling dips below Friday's 31-year low amid ...   
1985  Brexit cost investors $2 trillion, the worst o...   
1986  A Muslim Shop in the UK Was Just Firebombed Wh...   
1987  Palestinian terrorist stabs israeli teen girl ...   

                                                   Top7  \
1983  Rich Getting Richer at the Expense of the Poor...   
1984  No negative news about South African President...   
1985  Hong Kong democracy activists call for return ...   
1986  Mexican Authorities Sexually Torture Women in ...   
1987  Puerto Rico will default on $1 billion of debt...   

                                                   Top8  ...  \
1983  Spanish minister calls for Gibraltar to be ret...  ...   
1984  Surge in Hate Crimes in the U.K. Following U.K...  ...   
1985  Brexit: Iceland president says UK can join 'tr...  ...   
1986            UK shares and pound continue to recover  ...   
1987  Republic of Ireland fans to be awarded medal f...  ...   

                                                  Top16  \
1983  Sinn Fein calls for a referendum on Irish reun...   
1984  German lawyers to probe Erdogan over alleged w...   
1985  US, Canada and Mexico pledge 50% of power from...   
1986  Escape Tunnel, Dug by Hand, Is Found at Holoca...   
1987  Googles free wifi at Indian railway stations i...   

                                                  Top17  \
1983  $70 billion wiped off the Australian sharemark...   
1984  Boris Johnson says the UK will continue to "in...   
1985  There is increasing evidence that Australia is...   
1986  The land under Beijing is sinking by as much a...   
1987  Mounting evidence suggests 'hobbits' were wipe...   

                                                  Top18  \
1983  Nigel Farage disowns Vote Leave '350m for the ...   
1984  Richard Branson is calling on the UK governmen...   
1985  Richard Branson, the founder of Virgin Group, ...   
1986  Car bomb and Anti-Islamic attack on Mosque in ...   
1987  The men who carri

In [7]:
# Finding Missing Values
miss_value_row_list=[]
for i in tops.columns:
    for j in range(len(data_new)):
        if type(data_new[str(i)][j]) is str: # Non-missing values will have str type
            continue
        else: 
            print('Column Name: ' + str(i))
            print( 'Row ' + str(j))
            miss_value_row_list.append(j)
    miss_value_row_list= list(set(miss_value_row_list)) # Removing repeating elements(row number) 
print('\n')
print("Row numbers with missing valus :" + str(miss_value_row_list))

Column Name: Top23
Row 277
Column Name: Top24
Row 277
Column Name: Top24
Row 348
Column Name: Top24
Row 681
Column Name: Top25
Row 277
Column Name: Top25
Row 348
Column Name: Top25
Row 681


Row numbers with missing valus :[681, 348, 277]


In [8]:
# Removing rows with missing entries
data_new.drop(miss_value_row_list, inplace = True)

# Setting New Index for data_new
data_new= data_new.set_index(i for i in range(0, len(tops) - len(miss_value_row_list))) # After removing rows(with missing values) the index was not uniform, and hence index changed to total elements before[len(tops)] minus number of rows removed[len(miss_value_row_list)]

In [9]:
# Difrence in Encoded entries and normal str entries 
data_new['Top1'][0][0], data_new['Top1'][0][1]

('b', '"')

In [10]:
# Converting all the encoded news text(b'') to normal str 
for i in tops.columns:
    for j in range(len(data_new)):
        if data_new[str(i)][j][0]== 'b' and (data_new[str(i)][j][1]== '"' or data_new[str(i)][j][1]=="'"): # It is encoded text if entry: b'_' or b"_"
            data_new[str(i)][j]= data_new[str(i)][j][2:-1] # Removing b'' and b""

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """


In [11]:
# Combining all test of Top1, Top2..., Top25 in date-wise order  
top25_news= []
for i in range(len(data_new)):
    news_list=[]
    for j in tops.columns:
        news= data_new[str(j)][i]
        news_list.append(news)
    news_list= ' '.join(news_list)
    top25_news.append(news_list)

In [12]:
# Adding new column to data_new with all comments stacked tohgether for a particular date
data_new.insert(2, "Top 25 News", top25_news)

data_new.head()

Date  Label                                        Top 25 News  \
0  2008-08-11      1  Georgia 'downs two Russian warplanes' as count...   
1  2008-08-12      0  Why wont America and Nato help us? If they won...   
2  2008-08-13      0  Remember that adorable 9-year-old who sang at ...   
3  2008-08-14      1   U.S. refuses Israel weapons to attack Iran: r...   
4  2008-08-15      1  All the experts admit that we should legalise ...   

                                                Top1  \
0  Georgia 'downs two Russian warplanes' as count...   
1  Why wont America and Nato help us? If they won...   
2  Remember that adorable 9-year-old who sang at ...   
3   U.S. refuses Israel weapons to attack Iran: r...   
4  All the experts admit that we should legalise ...   

                                                Top2  \
0               BREAKING: Musharraf to be impeached.   
1           Bush puts foot down on Georgian conflict   
2                    Russia 'ends Georgia operation'   
3  When the president ordered to attack Tskhinval...   
4  War in South Osetia - 89 pictures made by a Ru...   

                                                Top3  \
0  Russia Today: Columns of troops roll into Sout...   
1  Jewish Georgian minister: Thanks to Israeli tr...   
2  "If we had no sexual harassment we would have ...   
3   Israel clears troops who killed Reuters camer...   
4  Swedish wrestler Ara Abrahamian throws away me...   

                                                Top4  \
0  Russian tanks are moving towards the capital o...   
1  Georgian army flees in disarray as Russians ad...   
2  Al-Qa'eda is losing support in Iraq because of...   
3  Britain\'s policy of being tough on drugs is "...   
4  Russia exaggerated the death toll in South Oss...   

                                                Top5  \
0  Afghan children raped with 'impunity,' U.N. of...   
1         Olympic opening ceremony fireworks 'faked'   
2  Ceasefire in Georgia: Putin Outmaneuvers the West   
3  Body of 14 year old found in trunk; Latest (ra...   
4  Missile That Killed 9 Inside Pakistan May Have...   

                                                Top6  \
0  150 Russian tanks have entered South Ossetia w...   
1  What were the Mossad with fraudulent New Zeala...   
2  Why Microsoft and Intel tried to kill the XO $...   
3  China has moved 10 *million* quake survivors i...   
4  Rushdie Condemns Random House's Refusal to Pub...   

                                                Top7  ...  \
0  Breaking: Georgia invades South Ossetia, Russi...  ...   
1  Russia angered by Israeli military sale to Geo...  ...   
2  Stratfor: The Russo-Georgian War and the Balan...  ...   
3  Bush announces Operation Get All Up In Russia'...  ...   
4  Poland and US agree to missle defense deal. In...  ...   

                                               Top16  \
0  Georgia Invades South Ossetia - if Russia gets...   
1  Israel and the US behind the Georgian aggression?   
2  U.S. troops still in Georgia (did you know the...   
3                         Elephants extinct by 2020?   
4  Bank analyst forecast Georgian crisis 2 days e...   

                                               Top17  \
0                   Al-Qaeda Faces Islamist Backlash   
1  "Do not believe TV, neither Russian nor Georgi...   
2          Why Russias response to Georgia was right   
3  US humanitarian missions soon in Georgia - if ...   
4  Georgia confict could set back Russia's US rel...   

                                               Top18  \
0  Condoleezza Rice: "The US would not act to pre...   
1  Riots are still going on in Montreal (Canada) ...   
2  Gorbachev accuses U.S. of making a "serious bl...   
3                Georgia's DDOS came from US sources   
4  War in the Caucasus is as much the product of ...   

                                               Top19  \
0  This is a busy day:  The European Union has ap...   
1       China to overtake US as largest manufa

In [13]:
# Creating a new dataset(data_final) with just the required columns
data_all_news= data_new[["Date", "Label", "Top 25 News"]]
display(data_all_news.head())
display(data_all_news.tail())

Date  Label                                        Top 25 News
0  2008-08-11      1  Georgia 'downs two Russian warplanes' as count...
1  2008-08-12      0  Why wont America and Nato help us? If they won...
2  2008-08-13      0  Remember that adorable 9-year-old who sang at ...
3  2008-08-14      1   U.S. refuses Israel weapons to attack Iran: r...
4  2008-08-15      1  All the experts admit that we should legalise ...

Date  Label                                        Top 25 News
1980  2016-06-27      0  David Cameron to Resign as PM After EU Referen...
1981  2016-06-28      1  Barclays and RBS shares suspended from trading...
1982  2016-06-29      1  2,500 Scientists To Australia: If You Want To ...
1983  2016-06-30      1  Explosion At Airport In Istanbul Yemeni former...
1984  2016-07-01      1  Jamaica proposes marijuana dispensers for tour...

# NLP Techniques

In [14]:
# Cleanig all the news(stacked together)
corpus=[]
for i in range(len(data_all_news)):
    news= re.sub('[^a-zA-Z]', ' ', data_all_news['Top 25 News'][i])
    news= news.lower()
    news= news.split()
    news=[word for word in news if not word in set(stopwords.words('english'))]
    lemmatizer = WordNetLemmatizer()
    news=[lemmatizer.lemmatize(word)for word in news if not word in set(stopwords.words('english'))]
    news= ' '.join(news)
    corpus.append(news)

In [15]:
# Loading TF-IDF model saved in "Stock News Sentiment"
tfidf_model = joblib.load('../input/stock-news-sentiment-pkl/TFIDF_model.pkl')
X_news = tfidf_model.transform(corpus).toarray()

In [16]:
# Loading the sentiment classifier model(saved in "Stock News Sentiment")
sentiment_model= joblib.load('../input/stock-news-sentiment-pkl/txt_sentiment.pkl')

In [17]:
# Getting class probablities for each news(in X_news i.e in Top 25 News)
negative= []
positive= []
neutral= []

for i in range(len(X_news)):
    k= sentiment_model.predict_proba(X_news[i].reshape(1, -1))
    negative.append(round(k[0][0]*10, 2))
    positive.append(round(k[0][1]*10, 2))
    neutral.append(round(k[0][2]*10, 2))
    

# Creating final dataset

In [18]:
# Adding new rows with sentiment probablities
data_all_news.insert(2, "Negative", negative)
data_all_news.insert(2, "Positive", positive)
data_all_news.insert(2, "Neutral", neutral)

In [19]:
data_final= data_all_news[["Label", "Negative", "Positive", "Neutral"]] 
data_final.head()
data_final.tail()

Label  Negative  Positive  Neutral
1980      0      2.19      4.63     3.18
1981      1      1.39      5.63     2.98
1982      1      1.97      6.25     1.78
1983      1      1.68      5.44     2.88
1984      1      1.19      5.83     2.98

# Data splitting

In [20]:
X= data_all_news[["Negative", "Positive", "Neutral"]]
Y= data_all_news['Label']
Y= Y.astype('int')

In [21]:
#Spliting Dataset into Training and Test sets
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test= train_test_split(X, Y, test_size=0.20, random_state=0)

# Classification Algorithms

In [22]:
# Random Forest
from sklearn.ensemble import RandomForestClassifier 
classifier= RandomForestClassifier(n_estimators= 500, criterion= 'entropy', random_state= 0) 
classifier.fit(X_train, Y_train)

# Predicting the test set result
y_pred= classifier.predict(X_test)
display(y_pred)

# Making the Confusion matrix
from sklearn.metrics import confusion_matrix
cm= confusion_matrix(Y_test, y_pred)
display(cm)

Accuracy= (cm[0][0] + cm[1][1])/(cm[0][0] + cm[1][1] + cm[0][1] + cm[1][0])
display(Accuracy)

array([1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1,

array([[ 67, 114],
       [ 99, 117]])

0.4634760705289673

In [23]:
# Decision Tree  
from sklearn.tree import DecisionTreeClassifier
classifier= DecisionTreeClassifier(criterion= 'entropy', random_state= 0)
classifier.fit(X_train, Y_train)

# Predicting the test set result
y_pred= classifier.predict(X_test)
display(y_pred)

# Making the Confusion matrix
from sklearn.metrics import confusion_matrix
cm= confusion_matrix(Y_test, y_pred)
display(cm)

Accuracy= (cm[0][0] + cm[1][1])/(cm[0][0] + cm[1][1] + cm[0][1] + cm[1][0])
display(Accuracy)

array([1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,

array([[ 69, 112],
       [108, 108]])

0.44584382871536526

In [24]:
# Kernel SVM
from sklearn.svm import SVC 
classifier= SVC(kernel='rbf', random_state= 0)
classifier.fit(X_train, Y_train)

# Predicting the test set result
y_pred= classifier.predict(X_test)
display(y_pred)

# Making the Confusion matrix
from sklearn.metrics import confusion_matrix
cm= confusion_matrix(Y_test, y_pred)
display(cm)

Accuracy= (cm[0][0] + cm[1][1])/(cm[0][0] + cm[1][1] + cm[0][1] + cm[1][0])
display(Accuracy)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

array([[  0, 181],
       [  0, 216]])

0.5440806045340051

In [25]:
# KNN
from sklearn.neighbors import KNeighborsClassifier
classifier= KNeighborsClassifier(n_neighbors= 7, metric='minkowski', p=2, leaf_size=70, weights= 'distance', algorithm= 'brute')
classifier.fit(X_train, Y_train)

# Predicting the test set result
y_pred= classifier.predict(X_test)
display(y_pred)

# Making the Confusion matrix
from sklearn.metrics import confusion_matrix
cm= confusion_matrix(Y_test, y_pred)
display(cm)

Accuracy= (cm[0][0] + cm[1][1])/(cm[0][0] + cm[1][1] + cm[0][1] + cm[1][0])
display(Accuracy)

array([1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1,

array([[ 76, 105],
       [102, 114]])

0.47858942065491183

In [26]:
# Multinomial NB
from sklearn.naive_bayes import MultinomialNB
classifier=MultinomialNB()
classifier.fit(X_train, Y_train)

# Predicting the test set result
y_pred= classifier.predict(X_test)
display(y_pred)

# Making the Confusion matrix
from sklearn.metrics import confusion_matrix
cm= confusion_matrix(Y_test, y_pred)
display(cm)

Accuracy= (cm[0][0] + cm[1][1])/(cm[0][0] + cm[1][1] + cm[0][1] + cm[1][0])
display(Accuracy)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

array([[  2, 179],
       [  7, 209]])

0.5314861460957179

In [27]:
# SGDC
from sklearn.linear_model import SGDClassifier
classifier = SGDClassifier(loss='modified_huber', random_state=0, shuffle=True)
classifier = classifier.fit(X_train, Y_train)

# Predicting the test set result
y_pred= classifier.predict(X_test)
display(y_pred)

# Making the Confusion matrix
from sklearn.metrics import confusion_matrix
cm= confusion_matrix(Y_test, y_pred)
display(cm)

Accuracy= (cm[0][0] + cm[1][1])/(cm[0][0] + cm[1][1] + cm[0][1] + cm[1][0])
display(Accuracy)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

array([[  0, 181],
       [  0, 216]])

0.5440806045340051

In [28]:
# Gradient Boosting
from sklearn.ensemble import GradientBoostingClassifier
classifier = GradientBoostingClassifier()
classifier = classifier.fit(X_train, Y_train)

# Predicting the test set result
y_pred= classifier.predict(X_test)
display(y_pred)

# Making the Confusion matrix
from sklearn.metrics import confusion_matrix
cm= confusion_matrix(Y_test, y_pred)
display(cm)

Accuracy= (cm[0][0] + cm[1][1])/(cm[0][0] + cm[1][1] + cm[0][1] + cm[1][0])
display(Accuracy)

array([1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1,

array([[ 47, 134],
       [ 70, 146]])

0.48614609571788414

# Saving the best classifier

In [29]:
# # Saving the GradientBoostingClassifier for future
joblib.dump(classifier, "DJIA_news_impact.pkl")

['DJIA_news_impact.pkl']